# pre-requisite to run this lambda function is 
# 1. one bucket at the same region where you are running this lambda
# 2. jar file or code to run this lambda inside your bucket

# this cloudformation is used to create a lambda function
AWSTemplateFormatVersion: '2010-09-09'
# Resource to create a lambda function
Resources:
  SampleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: com.piyush.sms.lambda.CallBack::messagingRequest
      Code:
       S3Bucket: messaging-bucket-app
       S3Key: message-lambda-jar-with-dependencies.jar
      Runtime: java8
      Role: arn:aws:iam::751125203171:role/service-role/LambdaExecutionRole
      FunctionName: lambda-dev